FROM python:3.12.8-slim-bookworm

WORKDIR /BACKEND 


RUN apt-get update && \ 
    apt-get install -y --no-install-recommends \
    build-essential \
    gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY requirements.txt /


RUN pip install -r /requirements.txt


COPY . /BACKEND
